FROM appcelerator/alpine:20160726
COPY ./amp /usr/local/bin/amp
COPY ./amplifier /usr/local/bin/amplifier
COPY ./amp-agent /usr/local/bin/amp-agent
COPY ./amp-log-worker /usr/local/bin/amp-log-worker
COPY ./amplifier-gateway /usr/local/bin/amplifier-gateway
COPY ./swarm-server /usr/local/bin/swarm-server
COPY ./swarm-agent /usr/local/bin/swarm-agent
EXPOSE 50101
ENTRYPOINT []
CMD [ "amplifier", "--service"]
