// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/cmd/swarm-agent/agentgrpc/swarm-agent.proto
// DO NOT EDIT!

/*
Package agentgrpc is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/cmd/swarm-agent/agentgrpc/swarm-agent.proto

It has these top-level messages:
	GetNodeInfoRequest
	NodeInfo
*/
package agentgrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetNodeInfoRequest struct {
}

func (m *GetNodeInfoRequest) Reset()                    { *m = GetNodeInfoRequest{} }
func (m *GetNodeInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeInfoRequest) ProtoMessage()               {}
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NodeInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*GetNodeInfoRequest)(nil), "agentgrpc.GetNodeInfoRequest")
	proto.RegisterType((*NodeInfo)(nil), "agentgrpc.NodeInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for SwarmServerService service

type SwarmServerServiceClient interface {
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*NodeInfo, error)
}

type swarmServerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSwarmServerServiceClient(cc *grpc.ClientConn) SwarmServerServiceClient {
	return &swarmServerServiceClient{cc}
}

func (c *swarmServerServiceClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*NodeInfo, error) {
	out := new(NodeInfo)
	err := grpc.Invoke(ctx, "/agentgrpc.SwarmServerService/GetNodeInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SwarmServerService service

type SwarmServerServiceServer interface {
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*NodeInfo, error)
}

func RegisterSwarmServerServiceServer(s *grpc.Server, srv SwarmServerServiceServer) {
	s.RegisterService(&_SwarmServerService_serviceDesc, srv)
}

func _SwarmServerService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmServerServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agentgrpc.SwarmServerService/GetNodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmServerServiceServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SwarmServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agentgrpc.SwarmServerService",
	HandlerType: (*SwarmServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _SwarmServerService_GetNodeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/cmd/swarm-agent/agentgrpc/swarm-agent.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x72, 0x4f, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2c, 0x28, 0x48, 0x4e, 0xcd, 0x49, 0x2d, 0x4a,
	0x2c, 0xc9, 0x2f, 0xd2, 0x4f, 0xcc, 0x2d, 0xd0, 0x4f, 0xce, 0x4d, 0xd1, 0x2f, 0x2e, 0x4f, 0x2c,
	0xca, 0xd5, 0x4d, 0x4c, 0x4f, 0xcd, 0x2b, 0xd1, 0x07, 0x93, 0xe9, 0x45, 0x05, 0xc9, 0xc8, 0xa2,
	0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x9c, 0x70, 0x49, 0x25, 0x11, 0x2e, 0x21, 0xf7, 0xd4,
	0x12, 0xbf, 0xfc, 0x94, 0x54, 0xcf, 0xbc, 0xb4, 0xfc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12,
	0x25, 0x39, 0x2e, 0x0e, 0x98, 0x90, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x6d, 0x14, 0xc9, 0x25, 0x14, 0x0c, 0x32, 0x35, 0x38, 0xb5,
	0xa8, 0x2c, 0xb5, 0x08, 0x44, 0x66, 0x26, 0xa7, 0x0a, 0x39, 0x73, 0x71, 0x23, 0x99, 0x25, 0x24,
	0xab, 0x07, 0xb7, 0x46, 0x0f, 0xd3, 0x0e, 0x29, 0x61, 0x24, 0x69, 0x98, 0x9c, 0x12, 0x43, 0x12,
	0x1b, 0xd8, 0x89, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0x3a, 0x5a, 0x98, 0xed, 0x00,
	0x00, 0x00,
}
