// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/cmd/swarm-server/servercore/swarm-server.proto
// DO NOT EDIT!

/*
Package servercore is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/cmd/swarm-server/servercore/swarm-server.proto

It has these top-level messages:
	SwarmMes
	DeclareRequest
	ServerRet
*/
package servercore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SwarmMes struct {
	Function string            `protobuf:"bytes,1,opt,name=function" json:"function,omitempty"`
	Args     map[string]string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data     []byte            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *SwarmMes) Reset()                    { *m = SwarmMes{} }
func (m *SwarmMes) String() string            { return proto.CompactTextString(m) }
func (*SwarmMes) ProtoMessage()               {}
func (*SwarmMes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SwarmMes) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

type DeclareRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeclareRequest) Reset()                    { *m = DeclareRequest{} }
func (m *DeclareRequest) String() string            { return proto.CompactTextString(m) }
func (*DeclareRequest) ProtoMessage()               {}
func (*DeclareRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ServerRet struct {
	Ack bool `protobuf:"varint,1,opt,name=ack" json:"ack,omitempty"`
}

func (m *ServerRet) Reset()                    { *m = ServerRet{} }
func (m *ServerRet) String() string            { return proto.CompactTextString(m) }
func (*ServerRet) ProtoMessage()               {}
func (*ServerRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*SwarmMes)(nil), "servercore.SwarmMes")
	proto.RegisterType((*DeclareRequest)(nil), "servercore.DeclareRequest")
	proto.RegisterType((*ServerRet)(nil), "servercore.ServerRet")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for SwarmServerService service

type SwarmServerServiceClient interface {
	GetStream(ctx context.Context, opts ...grpc.CallOption) (SwarmServerService_GetStreamClient, error)
	DeclareAgent(ctx context.Context, in *DeclareRequest, opts ...grpc.CallOption) (*ServerRet, error)
}

type swarmServerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSwarmServerServiceClient(cc *grpc.ClientConn) SwarmServerServiceClient {
	return &swarmServerServiceClient{cc}
}

func (c *swarmServerServiceClient) GetStream(ctx context.Context, opts ...grpc.CallOption) (SwarmServerService_GetStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SwarmServerService_serviceDesc.Streams[0], c.cc, "/servercore.SwarmServerService/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &swarmServerServiceGetStreamClient{stream}
	return x, nil
}

type SwarmServerService_GetStreamClient interface {
	Send(*SwarmMes) error
	Recv() (*SwarmMes, error)
	grpc.ClientStream
}

type swarmServerServiceGetStreamClient struct {
	grpc.ClientStream
}

func (x *swarmServerServiceGetStreamClient) Send(m *SwarmMes) error {
	return x.ClientStream.SendMsg(m)
}

func (x *swarmServerServiceGetStreamClient) Recv() (*SwarmMes, error) {
	m := new(SwarmMes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *swarmServerServiceClient) DeclareAgent(ctx context.Context, in *DeclareRequest, opts ...grpc.CallOption) (*ServerRet, error) {
	out := new(ServerRet)
	err := grpc.Invoke(ctx, "/servercore.SwarmServerService/DeclareAgent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SwarmServerService service

type SwarmServerServiceServer interface {
	GetStream(SwarmServerService_GetStreamServer) error
	DeclareAgent(context.Context, *DeclareRequest) (*ServerRet, error)
}

func RegisterSwarmServerServiceServer(s *grpc.Server, srv SwarmServerServiceServer) {
	s.RegisterService(&_SwarmServerService_serviceDesc, srv)
}

func _SwarmServerService_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SwarmServerServiceServer).GetStream(&swarmServerServiceGetStreamServer{stream})
}

type SwarmServerService_GetStreamServer interface {
	Send(*SwarmMes) error
	Recv() (*SwarmMes, error)
	grpc.ServerStream
}

type swarmServerServiceGetStreamServer struct {
	grpc.ServerStream
}

func (x *swarmServerServiceGetStreamServer) Send(m *SwarmMes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *swarmServerServiceGetStreamServer) Recv() (*SwarmMes, error) {
	m := new(SwarmMes)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SwarmServerService_DeclareAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmServerServiceServer).DeclareAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servercore.SwarmServerService/DeclareAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmServerServiceServer).DeclareAgent(ctx, req.(*DeclareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SwarmServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "servercore.SwarmServerService",
	HandlerType: (*SwarmServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeclareAgent",
			Handler:    _SwarmServerService_DeclareAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _SwarmServerService_GetStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/cmd/swarm-server/servercore/swarm-server.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xed, 0xb6, 0x55, 0x9a, 0xb1, 0x88, 0x0c, 0x15, 0x42, 0x40, 0x29, 0xc1, 0x43, 0x2e, 0x26,
	0x52, 0x0f, 0x8a, 0xe0, 0xa1, 0xa8, 0x08, 0x82, 0x97, 0xf4, 0x17, 0x4c, 0xb7, 0x63, 0x2c, 0x6d,
	0x3e, 0x9c, 0x6c, 0x2a, 0xfd, 0x27, 0xfe, 0x03, 0xff, 0xa6, 0x64, 0xfb, 0x65, 0xa1, 0x97, 0xdd,
	0x37, 0x6f, 0xde, 0xbc, 0x7d, 0xcb, 0xc0, 0x5b, 0x32, 0x35, 0x9f, 0xd5, 0x38, 0xd4, 0x79, 0x1a,
	0x51, 0x51, 0x68, 0x9e, 0xb3, 0x90, 0xc9, 0x25, 0xa2, 0xb4, 0x88, 0x74, 0x3a, 0x89, 0xca, 0x6f,
	0x92, 0xf4, 0xba, 0x64, 0x59, 0xb0, 0x44, 0xab, 0x4b, 0xe7, 0xc2, 0x7b, 0x7c, 0x58, 0x48, 0x6e,
	0x72, 0x84, 0x5d, 0xdb, 0xff, 0x55, 0xd0, 0x19, 0xd5, 0x92, 0x77, 0x2e, 0xd1, 0x83, 0xce, 0x47,
	0x95, 0x69, 0x33, 0xcd, 0x33, 0x57, 0xf5, 0x55, 0xe0, 0xc4, 0xdb, 0x1a, 0x07, 0xd0, 0x26, 0x49,
	0x4a, 0xb7, 0xd9, 0x6f, 0x05, 0x27, 0x83, 0xcb, 0x70, 0xe7, 0x11, 0x6e, 0xe6, 0xc3, 0xa1, 0x24,
	0xe5, 0x4b, 0x66, 0x64, 0x19, 0x5b, 0x2d, 0x22, 0xb4, 0x27, 0x64, 0xc8, 0x6d, 0xf5, 0x55, 0xd0,
	0x8d, 0x2d, 0xf6, 0xee, 0xc0, 0xd9, 0xca, 0xf0, 0x0c, 0x5a, 0x33, 0x5e, 0xae, 0xdf, 0xaa, 0x21,
	0xf6, 0xe0, 0x68, 0x41, 0xf3, 0x8a, 0xdd, 0xa6, 0xe5, 0x56, 0xc5, 0x43, 0xf3, 0x5e, 0xf9, 0x57,
	0x70, 0xfa, 0xcc, 0x7a, 0x4e, 0xc2, 0x31, 0x7f, 0x55, 0x5c, 0x9a, 0xda, 0x3e, 0xa3, 0x94, 0xd7,
	0xe3, 0x16, 0xfb, 0x17, 0xe0, 0x8c, 0x6c, 0xb2, 0x98, 0x4d, 0x6d, 0x4f, 0x7a, 0x66, 0xfb, 0x9d,
	0xb8, 0x86, 0x83, 0x1f, 0x05, 0x68, 0xe3, 0xae, 0x44, 0xf5, 0x39, 0xd5, 0x8c, 0x8f, 0xe0, 0xbc,
	0xb2, 0x19, 0x19, 0x61, 0x4a, 0xb1, 0x77, 0xe8, 0x6f, 0xde, 0x41, 0xd6, 0x6f, 0x04, 0xea, 0x46,
	0xe1, 0x13, 0x74, 0xd7, 0xd1, 0x86, 0x09, 0x67, 0x06, 0xbd, 0xff, 0xda, 0xfd, 0xd0, 0xde, 0xf9,
	0x9e, 0xcf, 0x26, 0xaa, 0xdf, 0x18, 0x1f, 0xdb, 0xe5, 0xdc, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x41, 0x43, 0xf1, 0x9c, 0xea, 0x01, 0x00, 0x00,
}
